const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=path.join(__dirname,'../docs/cookbook'),K=require(base+'/kitchen.js'),T=require(base+'/transfer.js');
const raw=fs.readdirSync(base+'/catalog').filter(f=>/^\d+\.json$/.test(f)).flatMap(f=>JSON.parse(fs.readFileSync(base+'/catalog/'+f)));
const patch=JSON.parse(fs.readFileSync(base+'/catalog/repairs.json'));const all=raw.filter(r=>!patch.aliases[r.id]).map(r=>patch.recipes[r.id]||r);
test('reviewed aliases keep canonical provenance and never point to missing records',()=>{const aliases=JSON.parse(fs.readFileSync(path.join(__dirname,'../recipe-aliases.json')));assert.equal(aliases.length,4);for(const a of aliases){assert.ok(a.reason.length>30);assert.ok(!all.some(r=>r.id===a.id));const r=all.find(r=>r.id===a.canonicalId);assert.ok(r);assert.ok(r.sourceAliases.includes(a.id));assert.match(r.source,/Equivalent source retained/);}});
test('every published recipe validates without dropping long source names',()=>{assert.equal(all.length,40889);assert.equal(new Set(all.map(r=>r.id)).size,40889);for(const r of all){K.validate(r);assert.ok(r.description.trim());assert.ok(r.source.trim());}});
test('source repairs preserve exact ingredient text and method meaning without guessing yield',()=>{let count=0;for(const r of all)if(r.sourceWording){count++;assert.equal(r.servings,1);assert.match(r.yieldUnit,/yield unspecified/);assert.deepEqual(r.ingredients.map(i=>i.sourceText),r.sourceIngredients);assert.deepEqual(r.steps.map(s=>s.replace(/\{\{([^}]+)\}\}/g,(_,key)=>r.ingredients.find(i=>i.key===key).sourceText).toLowerCase()),r.sourceSteps.map(s=>s.toLowerCase()));}assert.equal(count,40800);});
test('saving twice is idempotent and preserves personal metadata',()=>{const r=structuredClone(all[0]);r.notes='My note';r.rating=5;r.versionNames={original:'Family version'};const result=T.merge([r],[all[0]]);assert.equal(result.recipes.length,1);assert.equal(result.recipes[0].notes,'My note');assert.equal(result.recipes[0].rating,5);assert.equal(result.recipes[0].versionNames.original,'Family version');});
test('authored repairs link every ingredient and preserve divided totals while scaling',()=>{const overrides=JSON.parse(fs.readFileSync(path.join(__dirname,'../content-overrides.json')));for(const {recipe:r} of overrides){K.validate(r);assert.ok(r.minutes>0&&r.servings>0);const refs=[...r.steps.join(' ').matchAll(/\{\{([^}|]+)(?:\|([\d.]+))?\}\}/g)];for(const i of r.ingredients){assert.ok(i.substitution);const uses=refs.filter(m=>m[1]===i.key);assert.ok(uses.length);const divided=uses.filter(m=>m[2]);if(divided.length)assert.equal(divided.reduce((n,m)=>n+Number(m[2]),0),1);assert.ok(uses.filter(m=>!m[2]).length<=1);}const doubled=require(base+'/core.js').scaled(r,r.servings*2);r.ingredients.forEach((i,n)=>assert.equal(doubled[n].amount,i.amount*2));assert.equal(T.merge([r],[r]).recipes.length,1);}});
